config/routes.rb
Rails.application.routes.draw do
  resources :recipes, :path => 'recetas' do
    put :favorite, on: :member
  end
  resources :categories, :path => 'categorias'
  resources :users
  devise_for :users, :controllers => {registrations:'registrations'}, :path => 'u'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#index'
  get 'afirmaciones/registro'
  get 'pages/recetas'
  get 'pages/ultimas'
  get 'pages/favoritas'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :recipes
end

app/models/favorite_recipe.rb
class FavoriteRecipe < ApplicationRecord
  belongs_to :recipe
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  def self.search(titulo)
  if titulo
    where('titulo like ?', "%#{titulo.capitalize}%")
  else
    all
  end
  end
  has_many :line_items, inverse_of: :order
  belongs_to :user, required: true
  belongs_to :category, required: true
  # Favorited by users
  has_many :favorite_recipes # just the 'relationships'
  has_many :favorited_by, through: :favorite_recipes, source: :user # the actual users favoriting a recipe
  has_attached_file :photo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
  # Favorite recipes of user
  has_many :favorite_recipes # just the 'relationships'
  has_many :favorites, through: :favorite_recipes, source: :recipe # the actual recipes a user favorites
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes
end

app/controllers/afirmaciones_controller.rb
class AfirmacionesController < ApplicationController
  def registro
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.fetch(:category, {})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def recetas
  end
  def ultimas
  end
  def favoritas
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy, :favorite]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipe = Recipe.search(params[:titulo])
    if params[:category].blank?
      @recipe = Recipe.all.order("created_at DESC")
    else
      @category_id = Category.find_by(nombre: params[:category]).id
      @recipe = Recipe.where(category_id: @category_id).order("created_at DESC")
    end
  end

  # Add and remove favorite recipes
  # for current_user
  def favorite
    type = params[:type]
    if type == "favorite"
      current_user.favorites << @recipe
      redirect_to pages_favoritas_path, notice: 'You favorited #{@recipe.name}'

    elsif type == "unfavorite"
      current_user.favorites.delete(@recipe)
      redirect_back fallback_location: root_path, notice: 'Unfavorited #{@recipe.name}'

    else
      # Type missing, nothing happens
      redirect_to :back, notice: 'Nothing happened.'
    end
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  # GET /recipes/new
  def new
    @recipe = current_user.recipes.build
  end

  # GET /recipes/1/edit
  def edit
  end


  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = current_user.recipes.build(recipe_params)

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to @recipe, notice: 'Su receta ha sido creada' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Su receta fue actualizada.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1
  # DELETE /recipes/1.json
  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Se ha eliminado su receta.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:titulo, :cuerpo, :ingredientes, :category_id, :user_id, :descripcion, :photo)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(
      :email,
      :password,
      :nombre,
      :apellido,
      :password_confirmation
    )
  end

  def after_sign_up_path_for(resource)
    afirmaciones_registro_path
  end

  def account_update_params
    params.require(:user).permit(
      :email,
      :password,
      :nombre,
      :apellido,
      :password_confirmation,
      :current_password
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/afirmaciones_helper.rb
module AfirmacionesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def titulo(text)
    content_for :titulo, text
  end
  def meta_tag(tag, text)
    content_for :"meta_#{tag}", text
  end

  def yield_meta_tag(tag, default_text='')
    content_for?(:"meta_#{tag}") ? content_for(:"meta_#{tag}") : default_text
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/afirmaciones/registro.html.erb
<div class="afirmacion" style="min-height:550px; width:100%">
  <div class="registro">
        <h2>Se ha registrado satisfactoriamente</h2>
        <h3>Inicie sesion con su nuevo usuario</h3>
        <button onclick="location.href='/u/sign_in'" type="button" name="button">Iniciar Sesion</button>
      </div>
</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div id="categorias">
  <div class="titulo">
    <h1>Categorias</h1>
  </div>
  <div class="categs">
    <% @categories = @categories.last(16) %>
    <% @categories.each do |f| %>
    <%= link_to f.nombre, f, class:"boton" %>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div id="todas">
  <div class="titulo">
    <h1><%= @category.nombre %></h1>
  </div>
  <div class="busqueda">
    <%= form_tag(recipes_path, :method => 'get', class:"my-2 my-lg-0") do %>
    <%= text_field_tag :titulo, params[:titulo], class:" busc mr-sm-2", placeholder:"Busca tu receta" %>
    <%= submit_tag 'Buscar', name: nil, class:"my-2 my-sm-0", style:"width: inherit; background-color:inherit;" %>
    <% end %>
  </div>
  <% @recipe = Recipe.where(category_id: @category).order("created_at DESC") %>
  <% @recipe.each do |f| %>
  <div class="mostrar">
    <ol>
    <li class="title"><h2><%=link_to f.titulo, f, class:'tit'%></h2></li>
    <li class="categ"><h5><%= f.category.nombre %></h5></li>
    <li class="user"><h6><%= f.user.nombre %> <%= f.user.apellido %></h6><% if f.photo.present? %>
    <%= image_tag f.photo.url(:thumb), style:"margin-left:50%; margin-right:auto" %>
  <% end %></li>
    <li class="descript"><p><%= truncate (f.descripcion), length: 5000 %></p></li>
    </ol>
  </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
<p>© RecetasFoie  |   Ezekiel Grosfeld</p>
</footer>

app/views/layouts/_nav.html.erb
<header class="navbar navbar-expand nav-recetas flex-column flex-md-row bd-navbar" style="position:sticky;top: 0;
position: -webkit-sticky;">
    <a class="navbar-brand" href="/">Foie</a>
    <div class="navbar-nav-scroll">
        <ul class="navbar-nav bd-navbar-nav flex-row">
          <% if ! current_user %>
          <li class="nav-item dropdown" style="text-align:center">
            <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Buscar Receta
        </a>
      <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="background-color: white; border:none; top:46px">
        <%= link_to "Todas", recipes_path, class:'dropdown-item1' %>
        <%= link_to "Categorias", pages_ultimas_path, class:'dropdown-item1' %>
        <%= link_to "Recientes", categories_path, class:'dropdown-item1' %>
            <li class="nav-item">
              <a class="nav-link" href="/u/sign_up">Registrarse</a>
            </li>
          <% end %>
            <% if current_user %>

              <li class="nav-item">
                <%= link_to "Receta Nueva", new_recipe_path, class:'nav-link' %>
              </li>
              <li class="nav-item dropdown" style="text-align:center">
                <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= current_user.nombre %> <%= current_user.apellido %>
            </a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="background-color: white; border:none; top:46px">
            <%= link_to "Mis Recetas", pages_recetas_path, class:'dropdown-item1' %>
            <%= link_to "Mis Favoritas", pages_favoritas_path, class:'dropdown-item1' %><hr>
            <%= link_to "Cerrar Sesion", destroy_user_session_path, class:'dropdown-item1', :method => 'delete' %>
          </div>
          </li>
          <% end %>
        </ul>
    </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head lang="es">
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-131753206-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-131753206-1');
    </script>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
      (adsbygoogle = window.adsbygoogle || []).push({
        google_ad_client: "ca-pub-3113291568870229",
        enable_page_level_ads: true
      });
    </script>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-MNTGR4K');</script>
<!-- End Google Tag Manager -->
    <meta name="viewport" content="width=device-width">
    <title><%= if content_for?(:titulo) then yield(:titulo) + ' | ' end %>
      Foie</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name='description'
      content='<%= yield_meta_tag(:description, 'Todas las recetas en una sola pagina web, Subi tus recetas y compartilas para que todos la vean, o simplemente busca la receta que queres!!') %>' />
    <meta name='keywords'
      content='<%= yield_meta_tag(:keywords, 'recetas,receta,foie,comida,rico,delicioso,como,hacer,cocina,trucos,ingredientes,pasos,defaults') %>' />

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body style="background-color: #fff">
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MNTGR4K"
      height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
    <%= render 'layouts/nav' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/favoritas.html.erb
<div id="todas">
  <div class="titulo">
    <h1>Mis Recetas Favoritas</h1>
  </div>
    <% @recipe = current_user.favorites %>
    <% @recipe.each do |f| %>
    <div class="mostrar">
      <ol>
      <li class="title"><h2><%=link_to f.titulo, f, class:'tit'%></h2></li>
      <li class="categ"><h5><%= f.category.nombre %></h5></li>
      <li class="user"><h6><%= f.user.nombre %> <%= f.user.apellido %></h6><% if f.photo.present? %>
      <%= image_tag f.photo.url(:thumb), style:"margin-left:50%; margin-right:auto" %>
    <% end %></li>
      <li class="descript"><p><%= truncate (f.descripcion), length: 5000 %></p></li>
      <li class="user"><h6><%= link_to "Quitar de Favoritas", favorite_recipe_path(f, type: "unfavorite"), method: :put %></h6></li>
      </ol>
    </div>
    <% end %>
</div>

app/views/pages/index.html.erb
<% if ! current_user %>
<div class="cover-container1 d-flex w-100 h-100 p-3 mx-auto flex-column">
  <main class="inner cover">
    <h1 class="cover-heading">Foie</h1>
    <p class="lead">Todas tus recetas en una sola página.<br>
    Comienza a guardar y compartir todas tur recetas con un solo click!</p>
    <p><%= link_to "Registrarse" ,new_user_registration_path %></p><br>
    <p class="lead">Ya estas registrado?</p>
    <p><%= link_to "Iniciar Sesion", new_user_session_path %></p>
  </main>
</div>
<% else %>
<div class="cover-container2 d-flex w-100 h-100 p-3 mx-auto flex-column">
  <main class="inner cover">
    <h1 class="cover-heading">Foie</h1>
    <p class="lead">Busque su receta.<br>
    </p><br>
    <div class="busqueda">
      <%= form_tag(recipes_path, :method => 'get', class:"my-2 my-lg-0") do %>
      <%= text_field_tag :titulo, params[:titulo], class:" busc mr-sm-2", placeholder:"Busca tu receta" %>
      <%= submit_tag 'Buscar', name: nil, class:"my-2 my-sm-0", style:"width: inherit; background-color:inherit;" %>
      <% end %>
    </div>
    <div class="re">
      <%= link_to "Todas" ,recipes_path, class:'recet' %>&nbsp &nbsp &nbsp &nbsp &nbsp
      <%= link_to "Categorias" ,categories_path, class:'recet' %>&nbsp &nbsp &nbsp &nbsp &nbsp
      <%= link_to "Recientes" ,pages_ultimas_path, class:'recet' %>
    </div>
  </main>
</div>
  <% end %>
</div>

app/views/pages/recetas.html.erb
<% @rec = User.find(current_user.id).recipes %>
<% if @rec.count == 0 %>
<div class="cover-container2 d-flex w-100 h-100 p-3 mx-auto flex-column">
  <main class="inner cover">
    <h1 class="cover-heading">Parece que todavia no hiciste ninguna receta</h1>
    <p class="lead">Empeza a publicar tu primera receta ahora<br>
    </p><br>
    <div class="re">
      <%= link_to "Receta nueva", new_recipe_path, class:'recet' %>
    </div>
  </main>
</div>
<% else %>
<div id="todas">
  <div class="titulo">
    <h1>Mis Recetas</h1>
  </div>
    <% @recipe = User.find(current_user.id).recipes.order("created_at DESC") %>
    <% @recipe.each do |f| %>
    <div class="mostrar">
      <ol>
      <li class="title"><h2><%=link_to f.titulo, f, class:'tit'%></h2></li>
      <li class="categ"><h5><%= f.category.nombre %></h5></li>
      <li class="user"><h6><%= f.user.nombre %> <%= f.user.apellido %></h6><% if f.photo.present? %>
      <%= image_tag f.photo.url(:thumb), style:"margin-left:50%; margin-right:auto" %>
    <% end %></li>
      <li class="descript"><p><%= truncate (f.descripcion), length: 5000 %></p></li>
      <li class="user"><h6><%= link_to "Eliminar",recipe_path(f), :method => 'delete', data: {confirm: 'Seguro que desea eliminar la receta?'} %> &nbsp&nbsp&nbsp <%= link_to "Editar", edit_recipe_path(f) %></h6></li>
      </ol>
    </div>
    <% end %>
  <% end %>
</div>

app/views/pages/ultimas.html.erb
<% @recipe = Recipe.last(8) %>
<div id="todas">
  <div class="titulo">
    <h1>Ultimas Recetas </h1>
  </div>
  <% @recipe.each do |f| %>
  <div class="mostrar">
    <ol>
    <li class="title"><h2><%=link_to f.titulo, f, class:'tit'%></h2></li>
    <li class="categ"><h5><%= f.category.nombre %></h5></li>
    <li class="user"><h6><%= f.user.nombre %> <%= f.user.apellido %></h6><% if f.photo.present? %>
    <%= image_tag f.photo.url(:thumb), style:"margin-left:50%; margin-right:auto" %>
  <% end %></li>
    <li class="descript"><p><%= truncate (f.descripcion), length: 5000 %></p></li>
    </ol>
  </div>
  <% end %>
</div>

app/views/recipes/edit.html.erb
<%= form_for @recipe do |f| %>
  <div id="articulo">
    <%= f.label 'Titulo' %><br>
    <%= f.text_field :titulo %><br>

    <%= f.label 'Descripcion' %><br>
    <%= f.text_area :descripcion %><br>

    <%= f.label 'Ingredientes' %><br>
    <%= f.text_area :ingredientes%><br>

    <%= f.label 'Pasos' %><br>
    <%= f.text_area :cuerpo %><br>

    <div class="field">
      <%= f.label "Foto (ignorar si ya la hay)" %>
      <%= f.file_field :photo %>
    </div>

    <%= f.submit "Editar", style:"margin-left:20%" %>
  </div>
<% end %>

app/views/recipes/index.html.erb
<div id="todas">
  <div class="titulo">
    <h1>Recetas</h1>
  </div>
  <div class="busqueda">
    <%= form_tag(recipes_path, :method => 'get', class:"my-2 my-lg-0") do %>
    <%= text_field_tag :titulo, params[:titulo], class:" busc mr-sm-2", placeholder:"Busca tu receta" %>
    <%= submit_tag 'Buscar', name: nil, class:"my-2 my-sm-0", style:"width: inherit; background-color:inherit;" %>
    <% end %>
  </div>
    <% @recipe = Recipe.search(params[:titulo]) %>
    <% @recipe.each do |f| %>
    <div class="mostrar">
      <ol>
      <li class="title"><h2><%=link_to f.titulo, f, class:'tit'%></h2></li>
      <li class="categ"><h5><%= f.category.nombre %></h5></li>
      <li class="user"><h6><%= f.user.nombre %> <%= f.user.apellido %></h6><% if f.photo.present? %>
      <%= image_tag f.photo.url(:thumb), style:"margin-left:50%; margin-right:auto" %>
    <% end %></li>
      <li class="descript"><p><%= truncate (f.descripcion), length: 5000 %></p></li>
      </ol>
    </div>
    <% end %>
    <% if @recipe.count == 0 %>
    <div class="d-flex w-100 h-100 p-3 mx-auto flex-column" style="text-align:center">
      <main class="inner cover">
        <h1 class="cover-heading">No hemos encontrado ninguna receta con ese nombre</h1>
        <p class="lead">Intentalo de nuevo<br>
        </p><br>
      </main>
    </div>
    <% end %>
</div>

app/views/recipes/new.html.erb
<div id="articulo-titulo">
  <h1>Nueva receta</h1><br>
</div>
<%= render 'form', recipe: @recipe %>

app/views/recipes/show.html.erb
<% content_for :titulo, @recipe.titulo %>
<% meta_tag :description, @recipe.descripcion %>
<% meta_tag :keywords, @recipe.titulo.split.join(',') %>
<div id="receta">
  <p id="notice"><%= notice %></p>
  <div class="cuerpo">
    <div class="titulo">
      <h1><%= @recipe.titulo %></h1>
      <h6><%= link_to @recipe.category.nombre, @recipe.category, class:"categ" %></h6><hr>
      <br><h5><%= @recipe.user.nombre %> <%= @recipe.user.apellido %></h5><h6><%= link_to "ver mas recetas suyas", @recipe.user, class:'user' %></h6>
    </div>
    <% if @recipe.photo.present? %>
  <p style="text-align:center"><%= image_tag @recipe.photo.url(:medium) %></p>
  <% end %>
    <div class="descript">
      <% @fav = @recipe.favorited_by.length %>
      <strong>&#9733 <%= @fav %></strong>
      <br><br><h3>Descripcion:</h3>
      <p><%= @recipe.descripcion %></p>
    </div>
    <div class="cuerpo-ingredientes">
      <ol>
        <div class="subtitulo">
          <h3>Ingredientes</h3>
        </div>
        <% @ing = @recipe.ingredientes.split("\n")%>
        <% @ing.each do |f| %>
        <br><li>&#9733 <%= f %></li>
        <% end %>
      </ol>
    </div>
    <div class="cuerpo-pasos">
      <ol>
        <div class="subtitulo">
          <h3>Pasos</h3>
        </div>
        <% @pasos = @recipe.cuerpo.split("\n") %>
        <% @pasos.each do |f| %>
        <br><li><%= f %></li><br>
        <% end %>
      </ol>
    </div>
    <% if current_user %>
    <%= link_to "Añadir a Favoritos", favorite_recipe_path(@recipe, type: "favorite"), style:"padding: 3.35%", method: :put %>
    <%end%>
  </div>
  </div>

app/views/users/show.html.erb
<div id="todas">
  <div class="titulo">
    <h1><%= @user.nombre %> <%= @user.apellido %></h1>
  </div>
  <% @recipe = @user.recipes.order("created_at DESC") %>
  <% @recipe.each do |f| %>
  <div class="mostrar">
    <ol>
    <li class="title"><h2><%=link_to f.titulo, f, class:'tit'%></h2></li>
    <li class="categ"><h5><%= f.category.nombre %></h5></li>
    <li class="user"><h6><%= f.user.nombre %> <%= f.user.apellido %></h6></li>
    <li class="descript"><p><%= truncate (f.descripcion), length: 5000 %></p></li>
    </ol>
  </div>
  <% end %>
</div>